### PR TITLE
[ignition-msgs-5] fix DSO missing from command line

### LINKED ISSUE #68: [ignition-msgs-5] compile error DSO missing from command line
While rebuilding gazebo classic packages I get the following error:
```bash
/sbin/ld: CMakeFiles/ign_msgs_gen.dir/Generator.cc.o: undefined reference to symbol '_ZN4absl12lts_2023012513hash_internal15MixingHashState28CombineLargeContiguousImpl64EmPKhm'
/sbin/ld: /usr/lib/libabsl_hash.so.2301.0.0: error adding symbols: DSO missing from command line
```
This error occurs while building _ignition-mgs-5_ and _gazebo_

### PR DESCRIPTION
**Pull request by muellerbernd**
patches #68
sorry for all my opened PRs . I have somehow messed up some so I had to close some and redo them again.

### CODE REVIEW

**Comment by lprobsth** [comment]
These changes also seem ok.

**Comment by joe-bfd** [comment]
This solves my issue

**Review by petronny — APPROVED** [review]
https://github.com/arch4edu/cactus/actions/runs/6210823536/job/16878366908

**Review by acxz — APPROVED** [review]
thx for looking into this and resolving it!

**Pull request merged**
