### PR TITLE
[gazebo] add legacy packages as gazebo deps

### PR DESCRIPTION
**Pull request by muellerbernd**

### CODE REVIEW

**Review by acxz — APPROVED** [review]
thx for the PR!

**Comment by acxz** [comment]
@alexdewar can you review and merge to the AUR?

**Comment by alexdewar** [comment]
In the process of trying to build-test this, I hit #59 :cry:. Any ideas?

**Comment by acxz** [comment]
@alexdewar friendly ping

if you don't have the bandwidth do you mind handing over maintainership of the `gazebo` package to me?

**Comment by alexdewar** [comment]
> @alexdewar friendly ping
> 
> if you don't have the bandwidth do you mind handing over maintainership of the `gazebo` package to me?

Yeah tbh I am a bit overloaded and I don't use Gazebo these days. I'll orphan the package.

Thanks for your help!

**Comment by acxz** [comment]
Thanks, picked it up!

**Pull request merged**
